### PR TITLE
Rename release_notes to release_docs

### PR DESCRIPTION
**Pull request by derobins**
For parity with HDF5. Also puts a few ancient documents in an OLD folder.

### CODE REVIEW

**Review by byrnHDF — CHANGES_REQUESTED** [review]
ci change needed: release.yml and tarball.yml uploads a copy of the NEWSLETTER.txt file

**Comment by derobins** [comment]
> ci change needed: release.yml and tarball.yml uploads a copy of the NEWSLETTER.txt file

Ah. I hate how my grep command doesn't dive into .github.

**Comment by byrnHDF** [comment]
> > ci change needed: release.yml and tarball.yml uploads a copy of the NEWSLETTER.txt file
> 
> Ah. I hate how my grep command doesn't dive into .github.

My eclipse goes into everywhere.

**Comment by derobins** [comment]
> > > ci change needed: release.yml and tarball.yml uploads a copy of the NEWSLETTER.txt file
> > 
> > 
> > Ah. I hate how my grep command doesn't dive into .github.
> 
> My eclipse goes into everywhere.

Fixed!

**Review by byrnHDF — APPROVED** [review]

**Pull request merged**
