### PR TITLE
hdf/test: Remove local prototypes by moving local only functions to before use

### PR DESCRIPTION
**Pull request by schwehr**
This gets rid of a few redundant prototypes.

### CODE REVIEW

**Review by byrnHDF — APPROVED** [review]

**Comment by derobins** [comment]
This is another one of those changes I'm on the fence about. Is this really better? In HDF5 we got sick of fragile function ordering and mandated function prototypes. In the tests it's probably okay since they are usually only used in the main function, but I'm not a hurry to go back to having to reorder unrelated code because I moved something. Maintaining the prototypes also sucks. I'm just not sure which one sucks *more*. Thoughts?

**Comment by bmribler** [comment]
> having to reorder unrelated code because I moved something
My opinion, this one is worse.

**Comment by schwehr** [comment]
For this type of stuff, I'm strongly in favor of removing them. The extra stuff adds up. Especially in testing, if there is an order dependency issue showing up, the compiler will complain and it frequently indicates a bug. Here for example, there is one prototype that I had to keep and it indicates there there is problem with a missing function in the headers for the tests.

**Comment by bmribler** [comment]
> a missing function in the headers for the tests.
Could you give me more info on this missing function?

**Comment by bmribler** [comment]
> > > a missing function in the headers for the tests.
> 
> > Could you give me more info on this missing function?
> 
> This:
> 
> ```c
> extern void test_mgr_dup_images();
> ```
> 
> https://github.com/HDFGroup/hdf4/blob/bb23516f05e764db2e8eeec59a429f1180bbe309/hdf/test/mgr.c#L1057
> 
> should be in a header as the function is actually here:
> 
> https://github.com/HDFGroup/hdf4/blob/bb23516f05e764db2e8eeec59a429f1180bbe309/hdf/test/tdupimgs.c
You're right, it should have been in tproto.h, my mistake.  I'll fix it.

**Comment by schwehr** [comment]
As discussed out-of-band, this PR does not match the style the HDF4 team wants, so I'm closing the PR.

**Pull request closed without merging**
