### PR TITLE
Remove strdup implementation

### PR DESCRIPTION
**Pull request by derobins**
Every platform we support has strdup, so this can be removed.

### CODE REVIEW

**Comment by derobins** [comment]
The priority is "high" because this creates warnings about duplicated symbols.

**Comment by schwehr** [comment]
Thanks! This will fix #446

**Review by schwehr — APPROVED** [review]
I deployed this change and it fixed the issue was running into.

**Comment by schwehr** [comment]
Not for this PR, but can `HIstrncpy` also be replaced with systems' [strncpy](https://cplusplus.com/reference/cstring/strncpy/)

**Comment by derobins** [comment]
> Not for this PR, but can `HIstrncpy` also be replaced with systems' [strncpy](https://cplusplus.com/reference/cstring/strncpy/)

Yes, but since there that function drops \0 in the last byte, there's a little extra work to spread that around the library. I figured I'd do that when I got back from vacation since that might open some cans of worms when it comes to inappropriate string handling.

**Pull request merged**
